# Generated by Django 3.0.1 on 2019-12-31 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('totGames', models.IntegerField()),
                ('completedGames', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StorGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(max_length=36, unique=True)),
                ('state', models.IntegerField()),
                ('createdAt', models.DateTimeField()),
                ('storicizedAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddIndex(
            model_name='storgame',
            index=models.Index(fields=['createdAt'], name='api_storgam_created_8bf824_idx'),
        ),
    ]
